---
title: "NMFS Offshore Wind-CPS"
author: "Kevin L. Stierhoff"
date: "`r Sys.Date()`"
output: html_document
---

```{r load-libraries-functions, error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
# Install and load pacman (library management package)
if (!require("pacman")) install.packages("pacman")

# Install and load required packages from CRAN ---------------------------------
pacman::p_load(tidyverse,lubridate,knitr,maps,kableExtra,scatterpie,marmap,
               rnaturalearth,shadowtext,here,leaflet,leafem,htmltools,
               leaflet.extras,maptools,mapview,fs,plotly,magick,
               lwgeom,bookdown,sf,rworldmap,rworldxtra,ggspatial)

# Install and load required packages from Github -------------------------------
# rnaturalearth data
pacman::p_load_gh("ropenscilabs/rnaturalearthdata")
pacman::p_load_gh("ropenscilabs/rnaturalearthhires")
```

```{r knitr-options,echo=FALSE}
# Set global knitr chunk options
if (.Platform$OS.type == "unix") {
  # Do not specify Cairo device for MacOS
  knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE,
                        fig.align = 'center', dev = "png", dpi = 150)
} else {
  knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE,
                        fig.align = 'center', dev = "png", dpi = 150,
                        dev.args = list(type = "cairo"))
}
```

```{r user-settings}
# Set ggplot2 theme
theme_set(theme_bw())
```


# Map Call Areas

```{r import-map-areas}
areas <- st_read(here("Data/GIS/CallAreas_OR_Outline_2022_04_22.shp")) %>% 
  st_transform(crs = 3310)

aliquots <- st_read(here("Data/GIS/CallArea_OR_BlocksAliquots_2022_04_22.shp")) %>% 
    st_transform(crs = 3310)

wpts <- st_read(here("Data/GIS/OR_CallAreas_Waypoints_2022_04_22.shp")) %>% 
    st_transform(crs = 3310)

# Quick map of OR area
ggplot() +
  geom_sf(data = areas) + 
  geom_sf(data = aliquots, aes(fill = Call_Area_)) 
```

